# Generated by Django 6.1.1 on 2026-10-01 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('given_date', models.DateField()),
                ('text', models.TextField()),
                ('certificate_image', models.ImageField(upload_to='certificates/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=150)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField(blank=True, null=True)),
                ('studying_now', models.BooleanField()),
                ('responsibilities', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(choices=[('A1', 'башталгыч'), ('A2', 'Негизги'), ('B1', 'Орто'), ('B2', 'Ортодон жогору'), ('C1', 'Жогорку'), ('C2', 'Эркин'), ('Эне-тил', 'Эне-тил')], default='A1', max_length=150)),
                ('languages', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField(blank=True, null=True)),
                ('working_format', models.CharField(choices=[('office', 'Офисе'), ('meantime', 'Аралыкта'), ('hybrid', 'Гибрид')], default='office', max_length=150)),
                ('achievements', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
