# Generated by Django 6.1.1 on 2026-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_app', '0002_certificates_education_languages_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='Level',
            field=models.CharField(choices=[('A1', 'Начальный'), ('A2', 'Базовый'), ('B1', 'Средний'), ('B2', 'Выше среднего'), ('C1', 'Продвинутый'), ('C2', 'Свободный'), ('Родной язык', 'Родной язык')], default='A1', max_length=150),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='working_format',
            field=models.CharField(choices=[('office', 'В офисе'), ('remote', 'Удалённо'), ('hybrid', 'Гибрид'), ('freelance', 'Фриланс'), ('part_time', 'Неполный рабочий день'), ('full_time', 'Полный рабочий день'), ('contract', 'По контракту'), ('internship', 'Стажировка'), ('flexible', 'Гибкий график')], default='office', max_length=150),
        ),
    ]
