services:

  web:
    build: .
    command: >
      bash -c "./manage.py collectstatic --noinput &&
      ./manage.py migrate &&
      gunicorn -b 0.0.0.0:8000 my_site.wsgi:application"
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    networks:
      - motion_network
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - motion_network
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:

networks:
  motion_network:
    name: motion_network